import gmsh
import math
import sys
import meshio

# Initialize Gmsh
gmsh.initialize()
gmsh.model.add("Tensile Test Specimen")

# Define dimensions
L_t = 5e-3 # Transition length
L_roundx = 15e-3
L_specimen = 80e-3 # Length of the test section
W_fix = 30e-3
W_specimen = 20e-3
t = 4    # Thickness
hole_center = (L_roundx + L_t + L_specimen/2, 0)
hole_radius = 4e-3  # Hole radius (4 mm diameter)
transition_radius = 25e-3  # Transition radius

# Define points
p1 = gmsh.model.geo.addPoint(0, 0, 0)
p2 = gmsh.model.geo.addPoint(0, -W_fix/2, 0)
p3 = gmsh.model.geo.addPoint(L_roundx, -W_specimen/2, 0)
p4 = gmsh.model.geo.addPoint(L_roundx + L_t,  -W_specimen/2, 0)
p5 = gmsh.model.geo.addPoint(L_roundx + L_t + L_specimen,  -W_specimen/2, 0)
p6 = gmsh.model.geo.addPoint(L_roundx + L_t + L_specimen,  W_specimen/2, 0)
p7 = gmsh.model.geo.addPoint(L_roundx + L_t,  W_specimen/2, 0)
p8 = gmsh.model.geo.addPoint(L_roundx,  W_specimen/2, 0)
p9 = gmsh.model.geo.addPoint(0, W_fix/2, 0)
p10 = gmsh.model.geo.addPoint(hole_center[0], hole_center[1], 0)

cp2 = gmsh.model.geo.addPoint(L_roundx, transition_radius * 4/5 + W_fix/2, 0)
cp1 = gmsh.model.geo.addPoint(L_roundx, -(transition_radius * 4/5 + W_fix/2), 0)


# Define lines
l1 = gmsh.model.geo.addLine(p1, p2)
l2arc = gmsh.model.geo.addCircleArc(p2, cp1, p3)
l3 = gmsh.model.geo.addLine(p3, p4)
l4 = gmsh.model.geo.addLine(p4, p5)
l5 = gmsh.model.geo.addLine(p5, p6)
l6 = gmsh.model.geo.addLine(p6, p7)
l7 = gmsh.model.geo.addLine(p7, p8)
l8arc = gmsh.model.geo.addCircleArc(p8, cp2, p9)
l9 = gmsh.model.geo.addLine(p9, p1)

# Hole definition
p_hole1 = gmsh.model.geo.addPoint(hole_center[0] + hole_radius, hole_center[1], 0)
p_hole2 = gmsh.model.geo.addPoint(hole_center[0] - hole_radius, hole_center[1], 0)
arc1 = gmsh.model.geo.addCircleArc(p_hole1, p10, p_hole2)
arc2 = gmsh.model.geo.addCircleArc(p_hole2, p10, p_hole1)

# Define curve loops and surfaces
outer_loop = gmsh.model.geo.addCurveLoop([l1, l2arc, l3, l4, l5, l6, l7, l8arc, l9])
hole_loop = gmsh.model.geo.addCurveLoop([arc1, arc2])
surface = gmsh.model.geo.addPlaneSurface([outer_loop, hole_loop])
gmsh.model.addPhysicalGroup(2, [surface], tag=1)
gmsh.model.addPhysicalGroup(1, [arc1, arc2], tag=2)
gmsh.model.addPhysicalGroup(1, [l1, l9], tag=3)
gmsh.model.addPhysicalGroup(1, [l5], tag=4)

# Synchronize and generate mesh
gmsh.model.geo.synchronize()
gmsh.option.setNumber("Mesh.CharacteristicLengthMin", 0.5e-2)  # Minimum element size
gmsh.option.setNumber("Mesh.CharacteristicLengthMax", 0.5e-2)  # Maximum element size
gmsh.model.mesh.generate(2)
gmsh.option.setNumber("General.Terminal", 0)

# Save to file
gmsh.write("tensile_test_specimen.msh")

# Finalize Gmsh
gmsh.finalize()
mesh = meshio.read("tensile_test_specimen.msh")  # Read the .msh file generated by Gmsh
meshio.write("tensile_test_specimen.xdmf", mesh)  # Convert and save it as XDMF